import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { createElement } from "react";
import { Card } from "../components/Card";
import { Header } from "../components/Header";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Meu Porquinho</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header></Header>
            <main className="mx-auto  max-w-5xl">
                <section className="px-8 flex flex-row flex-wrap justify-between">
                    <h2 className="inline-block w-full pt-5 pb-3 text-2xl font-bold font-fm-primary">
                        Porquinhos Populares
                    </h2>
                    <Card></Card>
                </section>
            </main>

            <footer className="fixed bottom-0 flex justify-center w-full">
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className=""
                >
                    Powered by{" "}
                    <span>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </>
    );
};

export default Home;
