/* eslint-disable @next/next/no-img-element */
import { v4 as randomUUID } from "uuid";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Card } from "../components/Card";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Meu Porquinho</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header></Header>
            <main className="mx-auto max-w-7xl pb-8 sm:min-h-[calc(100vh-9.5rem)]">
                <section id="most-popular" className="">
                    <h2 className="w-full pt-5 pb-3 text-2xl font-bold font-fm-primary">
                        Porquinhos Populares
                    </h2>
                    <ul className="px-8 grid grid-cols-3 gap-6">
                        <Card
                            id={randomUUID()}
                            title="Lorem ipsum dolor sit amet"
                            description="Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Duis vel feugiat lorem. In eleifend magna ut nulla ornare
                    suscipit. Maecenas vitae ullamcorper eros. Curabitur vitae
                    sem turpis. Sed dolor augue, viverra a massa et, iaculis
                    accumsan tortor. Etiam scelerisque feugiat tincidunt."
                            goal={5138}
                            achieved={4600}
                        ></Card>
                        <Card
                            id={randomUUID()}
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            id={randomUUID()}
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        {/* <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude.Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude.Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude.Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude.Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card>
                        <Card
                            title="Amigos do Arthur"
                            description="Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude.Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude.Estamos fazendo uma vaquinha para ajudar no tratamento do nosso amigo arthur. Ele sofre de uma rara doença chamada LEIAUTISMO, cujo unico tratamento é com o Doutor Güntzel. Por favor, nos ajude"
                            goal={10000}
                            achieved={230}
                        ></Card> */}
                    </ul>
                </section>
            </main>

            <Footer />
        </>
    );
};

export default Home;
